name: Mirror to codeberg
on:
  push:
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0
      - name: Mirror to Codeberg
        run: |
          rm -rf .git/
          git init
          git add .
          git commit -m "based on latest release on https://github.com/visnkmr/homepagev2"
          git push -f origin https://visnk:${{secrets.CBERG_TOKEN}}@codeberg.org/visnk/pages.git main
